{% set name = "pooch" %}
{% set version = "1.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de46729579b9857ffd3e741987a2f6d5e0e03219892c167c6578c0091fb511ed

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - toml
  run:
    - python
    - platformdirs >=2.5.0
    - packaging >=20.0
    - requests >=2.19.0
  run_constrained:
    # progress
    - tqdm >=4.41.0,<5.0.0
    # sftp
    - paramiko >=2.7.0
    # xxhash
    - xxhash >=1.4.3

# E       fixture 'ftpserver' not found
# pytest-localftpserver is not a part of the Anaconda main channel.
{% set disabled_tests = " not test_check_availability_on_ftp" %}
{% set disabled_tests = disabled_tests + " and not test_ftp_downloader" %}

# requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://figshare.com/articles/dataset/Test_data_for_the_Pooch_library/14763051/1
{% set disabled_tests = disabled_tests + " and not test_pooch_custom_url" %}
{% set disabled_tests = disabled_tests + " and not test_pooch_download" %}
{% set disabled_tests = disabled_tests + " and not test_load_registry_from_doi" %}
{% set disabled_tests = disabled_tests + " and not test_figshare_url_file_not_found" %}
{% set disabled_tests = disabled_tests + " and not test_doi_downloader" %}
{% set disabled_tests = disabled_tests + " and not test_figshare_unspecified_version" %}
{% set disabled_tests = disabled_tests + " and not test_figshare_data_repository_versions" %}
{% set disabled_tests = disabled_tests + " and not test_create_and_fetch" %}
{% set disabled_tests = disabled_tests + " and not test_figshare_url_file_not_found" %}  # [osx]
{% set disabled_tests = disabled_tests + " and not test_doi_downloader" %}  # [osx]

test:
  requires:
    - pytest
    - pip
    - pytest-httpserver
  imports:
    - pooch
  commands:
    - pytest --pyargs -vv pooch.tests -k "{{ disabled_tests }}"
    - pip check

about:
  home: https://github.com/fatiando/pooch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A friend to fetch your data files
  description: |
    Pooch manages your remote data files. It automatically downloads and stores
    them in a local directory (using HTTP or FTP), with support for versioning,
    corruption checks, and custom download and post-processing operations.
  doc_url: https://www.fatiando.org/pooch
  dev_url: https://github.com/fatiando/pooch

extra:
  recipe-maintainers:
    - leouieda
    - dopplershift
